{% set name = "gridtk" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gridtk-{{ version }}.tar.gz
  sha256: 3d7fb55cf8330251aa06c3916fab26ebe12d2343269777aa82774d8c530f3f34

build:
  entry_points:
    - jman = gridtk.script.jman:main
    - qconf = gridtk.script.grid:main
    - qsub = gridtk.script.grid:main
    - qdel = gridtk.script.grid:main
    - qstat = gridtk.script.grid:main
    - qrsh = gridtk.script.grid:main
    - qhost = gridtk.script.grid:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >=3.9
    - clapper
    - sqlalchemy <2
    - __unix

test:
  source_files:
    - tests
  imports:
    - gridtk
  commands:
    - pip check
    - jman --help
    - pytest -sv tests
  requires:
    - pip
    - pytest

about:
  home: https://pypi.org/project/gridtk/
  doc_url: https://gridtk.readthedocs.io
  dev_url: https://gitlab.idiap.ch/software/gridtk
  summary: SGE Grid-enabled job submitter and execution monitor
  license: GPL-3.0-or-later
  license_file: LICENSES/GPL-3.0-or-later.txt

extra:
  recipe-maintainers:
    - anjos
